### ISSUE TITLE
Old version - not secure connection

### ISSUE THREAD

**Issue by VincentGreffe** [evolgeniusteam/EvolviewDocumentation#13]
Dear, 

I noticed that I'm unable to log in into the old version of Evolview (probably due to the fact the there is an not secure connection).
Is it possible to change this?

Kind regards,

Vincent

**Comment by evolgeniusteam** [comment]
Dear Vincent,

Social login is known not working in the old version (ver2), please use the latest version instead. For unknown reasons, we could not fix the login issue of the version 2, my apology for the inconveniences. 

Best,

**Comment by evolgeniusteam** [comment]
Dear Vincent,

My apology for the inconveniences. Regular login is now working for ver2. We have also switched to secure connections with the 'https' protocol.

Thank you for using Evolview.
