### ISSUE TITLE
地址打不开了

### ISSUE THREAD

**Issue by biopig** [evolgeniusteam/EvolviewDocumentation#19]
http://120.202.110.254:8280/evolview  
这个地址卡不开了，
http://www.evolgenius.info/evolview
这个还可以用

**Comment by balaram26** [comment]
Hi ,the mirror site (http://120.202.110.254:8280/evolview)is currently down,but the main site(http://www.evolgenius.info/evolview) is online working and well. We are setting up secondary site for users who needs access to the data from mirror site. I will update here, once data from mirror site is also accessible online. @biopig you can contact us at evolgenius.team@gmail.com if You have specific questions related with mirror site data.

**Comment by balaram26** [comment]
Hi, i have uploaded the mirror link data and set up a working version 2 on the following address, you can use this link to access you mirror site project data using the same version of the software. [https://evolgenius.info//evolview-v2-m/#login](url)

Thank you,
Evolview Team
