### ISSUE TITLE
Excuse me，I can't login with account

### ISSUE THREAD

**Issue by zero0886mo** [evolgeniusteam/EvolviewDocumentation#20]
Dear,

I've used Evolview for a while now, and enjoyed it very much so far.
I wanted to use it again now, but I can't seem to login in. Are the servers down?
When I try to retrieve my password by using 'forgot password', they say it can't connect to the server.
My email address is 765999656@qq.com, looking forward to your reply. Thank you！

Kind regards,

mo

**Comment by balaram26** [comment]
Dear Evolview user, i have reset the password and have sent detailed email on how to reset the password. 

Best wishes,
Evolview Team.

**Comment by zero0886mo** [comment]
Dear engineer
Thank you very much for the tools you developed. When I use this tool, I feel it is very powerful and easy to use.
Thank you also for your team's maintenance of this tool, which solved my problem in such a short time, thanks again!
Thank you！ Best wishes！

**Comment by balaram26** [comment]
Dear user, thank you for your continued support.

Best wishes,
Evolview Team.
