### ISSUE TITLE
Leaf label decoration

### ISSUE THREAD

**Issue by SilasV123** [evolgeniusteam/EvolviewDocumentation#21]
Hi I am trying to add leaf decorations to a tree as I have before and this time around I cannot seem to get the unfilled shapes to display. 

For example:

Arthrobacter_koreensis_5J12A	"square,red:red"

results in a filled red square, however:

Arthrobacter_koreensis_5J12A	"square,white:red"

results in no observable leaf label.

I am not sure if I am doing something wrong here or not. Attached is my file used for leaf label decoration.

Thanks.
[all_pgpr_leafnodes7.txt](https://github.com/evolgeniusteam/EvolviewDocumentation/files/4388384/all_pgpr_leafnodes7.txt)

**Comment by evolgeniusteam** [comment]
please change "square" to "rect", and let me know if the problem persists.

Here are a list of supported shapes:

triangle
circle
rect
star
check

... please check more details at: https://www.evolgenius.info//evolview/helpsite/dat9.html

Cheers

**Comment by SilasV123** [comment]
Hi,

I have changed "square" to "rect" but it doesn’t seem to have had any effect. Attached is the new tree with “rect” labels vs a previous version of the tree from a few months back with the leaf labels as I am trying to get them.

Regards,
Silas

**Comment by evolgeniusteam** [comment]
in that case, please remove any quotes from your dataset.

See here for an example: https://www.evolgenius.info//evolview/#shared/silas_BQiGVZZZDE/user%20feedbacks%20:%20silas

Cheers

**Comment by SilasV123** [comment]
Yes! That has fixed it!

Thank you for your quick help.

Regards,
Silas
