### ISSUE TITLE
Problem with Upload data set " Leaf background color"  

### ISSUE THREAD

**Issue by Daniherrera77** [evolgeniusteam/EvolviewDocumentation#25]
Hello,
I cant upload a dataset to change the leaf background color.
I have this style of data: (Uniprot code + Hex color format)
**B0ZB56     # a618ff**

With the data set  " leaf labels"  works 

Thanks

Daniela

**Comment by evolgeniusteam** [comment]
it should be written as below, and separate the leaf name and color with a TAB.
B0ZB56	#a618ff

Cheers.
