### ISSUE TITLE
Leaf name do not support underline?

### ISSUE THREAD

**Issue by CuteZebra** [evolgeniusteam/EvolviewDocumentation#27]
Sometime the underline of gene_id will vanish.
e.g."NC_013790" becomes "NC 013790"
For shortcases as well as my personal tree files.

**Comment by evolgeniusteam** [comment]
currently underline symbols in leaf names are not *displayed*; however they are required for writing up datasets. My apology for the confusion.

**Comment by CuteZebra** [comment]
Thanks!

However, I did have the underline symbols in leaf names last week, and I lost it this week.

It's so hard to avoid underline symbols of gene_name or gene_id.  Could you please give me some suggestions? 



lkhcoffee@163.com
 
From: evolgeniusteam
Date: 2020-08-24 15:00
To: evolgeniusteam/EvolviewDocumentation
CC: CuteZebra; Author
Subject: Re: [evolgeniusteam/EvolviewDocumentation] Leaf name do not support underline? (#27)
currently underline symbols in leaf names are not displayed; however they are required for writing up datasets. My apology for the confusion.

**Comment by CuteZebra** [comment]
Sorry, I confuse myself. The leaf names had no underline symbols last week.

And I have already use "-" rather than "_" to fix the problem.

Anyway, I am looking forward to that Evolview will support underline symbols in the future.

Thanks a lot!



lkhcoffee@163.com
 
From: lkhcoffee@163.com
Date: 2020-08-24 15:10
To: evolgeniusteam/EvolviewDocumentation; evolgeniusteam/EvolviewDocumentation
CC: Author
Subject: Re: Re: [evolgeniusteam/EvolviewDocumentation] Leaf name do not support underline? (#27)
Thanks!

However, I did have the underline symbols in leaf names last week, and I lost it this week.

It's so hard to avoid underline symbols of gene_name or gene_id.  Could you please give me some suggestions? 



lkhcoffee@163.com
 
From: evolgeniusteam
Date: 2020-08-24 15:00
To: evolgeniusteam/EvolviewDocumentation
CC: CuteZebra; Author
Subject: Re: [evolgeniusteam/EvolviewDocumentation] Leaf name do not support underline? (#27)
currently underline symbols in leaf names are not displayed; however they are required for writing up datasets. My apology for the confusion.
