### ISSUE TITLE
Cannot log in to the system normally

### ISSUE THREAD

**Issue by pigmorning** [evolgeniusteam/EvolviewDocumentation#30]
I cannot log in to the system normally, nor can I use the password to reset the system.

**Comment by balaram26** [comment]
my apology for the inconvenience. the mail server was NOT set properly so that the reset-password function actually does not work.
please send your email address to me (evolgenius.team@gmail.com), I will reset your password manually.

**Comment by pigmorning** [comment]
I have sent the my email address through the e-mail on Sep. 24. You can check your email. Thank you!

**Comment by balaram26** [comment]
I had already reset the login details for an account that I got mail I received on 23rd September. Does ur email address ends with : ******382@qq.com  ? If yes,could you check your inbox for the mail I sent after resetting the login credentials?

**Comment by pigmorning** [comment]
Unfortunately, my email address is zhuchen19921118@126.com, there may be some problems in the process of sending emails. Can you reset my account?

**Comment by balaram26** [comment]
I have reset the password and have sent instructions to the registered email address. Let me know if the login issue has been resolved.

**Comment by pigmorning** [comment]
Thank you so much for your help, the account has been reset and can be used normally.

**Comment by balaram26** [comment]
Dear user, thank you for your continued support.

Best wishes,
Evolview Team.
