### ISSUE TITLE
Can't perform group label style 5

### ISSUE THREAD

**Issue by dineshkumarsrk** [evolgeniusteam/EvolviewDocumentation#34]
I would like to generate a circular tree with group labels similar to `group label style 5`, I could successfully draw group label style 4, but I could not understand the code details of `group label style 5` mentioned in the [documentation section](https://www.evolgenius.info/evolview/helpsite/dat12.html). Even I could not find `group label style 5` codes in the `DEMOS (22 trees) ` section, the `DEMOS` section has the codes up-to `group label style 4`. Therefore, kindly provide the example code for `group label style 5`.
Thank you.

**Comment by balaram26** [comment]
Hi, Thanks for using Evolview. There is example for group label style 5 on the user help pages. Here is a sample code for the style 5 along with example tree code:

Tree:
<pre>
`(chicken,((mouse,rat),(chimp,human)));`
</pre>

Group label style 5 example:

<pre>
`!grouplabel	style=5,color=pink,show=1,marginPCT=0.05,fontsize=14,fontcolor=white,fontitalic=0,textalign=middle,textorientation=horizontal,linewidth=2
!op	0.8
chicken	bkcolor=#404AC3,text=chicken
mouse	bkcolor=green,text=rodent,fontcolor=darkred
rat,human	bkcolor=#BE4144,text=mammal,textorientation=vertical,linewidth=4,fontsize=16`
</pre>
for the more information kindly check the the help page link at : [Help pages: Evolview Group label styles](https://www.evolgenius.info/evolview/helpsite/dat12.html)

I have also attached the screenshot of the example section along with the output tree below:

![Screenshot 2021-07-02 at 7 16 51 AM](https://user-images.githubusercontent.com/1926881/124208760-ddf3e480-db05-11eb-913d-ac5c70e2587d.png)

With regards,
Evolview Team

**Comment by balaram26** [comment]
Dear user, i hope the post helped you with your query. This post is closed due to longterm inactivity.

Evolview Team
