### ISSUE TITLE
After the drawing is completed, it cannot be saved on the account side 

### ISSUE THREAD

**Issue by yaohaihang** [evolgeniusteam/EvolviewDocumentation#39]
Hello!

Once we have finished the drawing, we cannot save it on our account, and when I go back to my account, the finished drawing is lost and I can only see the original, undecorated, bare tree

2. It is not possible to upload the exported diagram made on the previous website here, it keeps showing an error.

Thank you for your help!

Best regards

**Comment by balaram26** [comment]
Hii, may i know which version of the evolview are you using? is it the latest one or the old versions? there was a some backend issue before which was has been already solved some time ago. sorry for the inconvenience caused. Could you confirm if you still have the issue?

With Regards,
Evolview team.
