### ISSUE TITLE
sign in problem

### ISSUE THREAD

**Issue by davidku100** [evolgeniusteam/EvolviewDocumentation#41]
Hi,

    I have used Evolview for a period of time and I found it is very useful in formatting the trees.

    But recently, I found there is a login issue: I cannot login or register a new account.

    Could you please give me some help?

                                    
     david

**Comment by balaram26** [comment]
HI david,

We are sorry for the inconvenience caused.  I have checked the current version and version 3 for login/register issues . They seem to be working normal, so i assume it might be something related  with your login details. Could you provide us with your login email id to : evolgenius.team@gmail.com .

With Regards,
Evolgenius team.

**Comment by Orz-CQ** [comment]
Hi, 

I also find that I could not register or login in Evolview.
Is there still something wrong here?

Lan

**Comment by evolgeniusteam** [comment]
Dear Lan,

Can you send a request to this email (balaram26 ***@***.***>) using your registered email account? We will try manually reset your password on our server.

Cheers,

Weihua


---------------------------------
Wei-Hua Chen

Professor, PhD Supervisor,
Department of Bioinformatics and Systems Biology,
School of Life Science and Technology,
Huazhong University of Science and Technology (HUST)

**Comment by LanLBio** [comment]
Dear Weihua,

I am glad to receive from you.
While I tried my password and finally got login.
Thanks! Have a nice day!

Best,
Lan
