### ISSUE TITLE
How many colors does this software support? 

### ISSUE THREAD

**Issue by hym-wrq** [evolgeniusteam/EvolviewDocumentation#50]
How many colors does this software support? How can I color the tree labels according to the color code, such as Mahachaiensis#FA8072?

**Comment by hym-wrq** [comment]
I need 25 colors, but I don't know how to do it.

**Comment by evolgeniusteam** [comment]
thank you for using Evolview. 

Supported colors include: 
- All html color names (as listed here: https://www.w3schools.com/colors/colors_names.asp) and
-  hex colors similar to the one you mentioned 

you can also try rgb colors such as rgb(205, 92, 92).

**Comment by evolgeniusteam** [comment]
you can randomly choose the number of colors from the supported ones, or use color palettes available online such as https://colorhunt.co.

**Comment by evolgeniusteam** [comment]
hi, thank you for using Evolview.

supported colors include:

- html color names: https://www.w3schools.com/colors/colors_names.asp, and
- hex colors like #FA8072

you can also try RGB colors such as rgb(255, 0, 0) to see if it works.

You can pick any number of colors from the html colors, or use color palettes from https://colorhunt.co and similar web tools.
